### ISSUE TITLE
Apple Music Songs Crash

### ISSUE THREAD

**Issue by snake302** [Luccifer/BPM-Analyser#5]
Hi there!
Thanks for awesome bridge, but I found some issue:
If I pick song that **purchased** and downloaded from **iTunes Store** - everything is okay.
But if I am picking song that I have downloaded from **Apple Music** the library crashes: `"BPMAnalyser[4409:1894057] open error: iPod library error."`

My Apple Music subscription is active and songs are downloaded and stored in iPhone memory.

**Comment by Luccifer** [comment]
Привет, Аким! Давненько не виделись :)
На сколько я помню, у AppleMusic стоит дополнительная защита при воспроизведении файла, я вечерком гляну, что именно вызывает ошибку, но как мне кажется, это именно защитка.. в качестве подтверждения теории - можно попробовать стандартным плеером(в проекте который) просто воспроизвести любую музыку из AppleMusic, если не пойдёт, то скорее всего просто другое яблочное решение для воспроизведения музыки надо будет взять

**Comment by snake302** [comment]
Привет!) Да, сколько времени прошло - сейчас в телегу стукну) 

Я решил тему на английском сделать - что бы другие юзеры тоже могли увидеть)

**Comment by Luccifer** [comment]
All in all: The problem is because of Apple Music DRM-security using for songs you downloaded. Just use Apple Framework for Apple Music Library and call the player to be shown/play with Music/Apple Music respectively of you are using local music or iTunes/AppleMusic subscription.. Developer can't access Apple Music with Music.app avoiding the check and security channel of Apple Music Framework and functionality made by Apple.

Closed
